# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import datetime
import re


class TestUser():
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()



    def test_user_registry(self):
        self.driver.get("http://localhost/litecart/public_html/en/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.LINK_TEXT, "New customers click here").click()
        self.driver.find_element(By.NAME, "firstname").send_keys("Тест")
        self.driver.find_element(By.NAME, "lastname").send_keys("Тестович")
        self.driver.find_element(By.NAME, "address1").send_keys("Ул. Тестовая")
        self.driver.find_element(By.NAME, "postcode").send_keys("99950")
        self.driver.find_element(By.NAME, "city").send_keys("LA")
        self.driver.find_element(By.CLASS_NAME, "select2-selection__arrow").click()
        self.driver.find_element(By.CLASS_NAME, "select2-search__field").send_keys("United States")
        # self.driver.find_element(By.ID, "select2-country_code-vo-result-h286-US").click()
        self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys(Keys.ENTER)

        date_time = clear(str(datetime.datetime.now().time()))

        login = f"test{date_time}@test.test"
        password = 1
        self.driver.find_element(By.NAME, "email").send_keys(login)
        self.driver.find_element(By.NAME, "phone").send_keys("+79059059595")
        self.driver.find_element(By.NAME, "password").send_keys(password)
        self.driver.find_element(By.NAME, "confirmed_password").send_keys(password)
        self.driver.find_element(By.NAME, "create_account").click()
        self.logout()

        self.login(login, password)
        self.logout()

    def login(self, email, password):
        self.driver.find_element(By.NAME, "email").send_keys(email)
        self.driver.find_element(By.NAME, "password").send_keys(password)
        self.driver.find_element(By.NAME, "login").click()
    def logout(self):
        self.driver.find_element(By.XPATH, "//a[@href='http://localhost/litecart/public_html/en/logout']").click()




def clear(s):
    return re.sub("[() - : .]", "", s)


