# Generated by Selenium IDE
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test:
    def setup_method(self, ):
        #caps = DesiredCapabilities().CHROME
        #caps["pageLoadStrategy"] = "normal"
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, ):
        self.driver.quit()

    def test_open_new_window(self):
        self.driver.get(
            "http://localhost/litecart/public_html/admin/login.php?redirect_url=%2Flitecart%2Fpublic_html%2Fadmin%2F")

        # авторизоваться
        self.driver.set_window_size(1276, 729)
        self.driver.find_element(By.NAME, "username").clear()
        self.driver.find_element(By.NAME, "username").send_keys("admin")
        self.driver.find_element(By.NAME, "password").clear()
        self.driver.find_element(By.NAME, "password").send_keys("admin")
        self.driver.find_element(By.NAME, "login").click()

        # перейти в Страны
        WebDriverWait(self.driver, 5).until(
            expected_conditions.element_to_be_clickable((By.XPATH, "//span[text()='Countries']")))
        self.driver.find_element(By.XPATH, "//span[text()='Countries']").click()

        # ожидание элемента Add New Country и клик
        WebDriverWait(self.driver, 5).until(
            expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Add New Country")))
        self.driver.find_element(By.LINK_TEXT, "Add New Country").click()
        WebDriverWait(self.driver, 5).until(
            expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a:nth-child(4) > .fa-external-link")))

        # получить все кнопки с открытием новой страницы
        all_links= self.driver.find_elements(By.XPATH, "//td[@id='content']//form//a[@target='_blank']/i")

        for element in all_links:
            # открывает новое окно
            element.click()

            # получить данные об окнах
            window_before = self.driver.window_handles[0]
            window_after = self.driver.window_handles[1]

            # переключиться на новое окно
            self.driver.switch_to.window(window_after)
            new_window_link = self.driver.current_url
            if 'wikipedia.org' in new_window_link:
                WebDriverWait(self.driver, 5).until(
                    expected_conditions.presence_of_element_located((By.XPATH, "//img[@alt='Wikipedia']")))
            elif 'www.informatica.com' in new_window_link:
                WebDriverWait(self.driver, 5).until(
                    expected_conditions.presence_of_element_located((By.CLASS_NAME, "infa-h-default-logo")))
            self.driver.close()
            self.driver.switch_to.window(window_before)
            WebDriverWait(self.driver, 5).until(
                expected_conditions.presence_of_element_located(
                    (By.CSS_SELECTOR, "a:nth-child(4) > .fa-external-link")))
            link = self.driver.current_url
            assert 'app=countries&doc=edit_country' in link

