# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import datetime
import re


class Test:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_geozones_check(self):
        self.driver.get("http://localhost/litecart/public_html/admin/")
        login = 'admin'
        password = 'admin'
        self.driver.set_window_size(1236, 950)
        self.login_admin_panel(email=login, password=password)

        # перейти в геозоны
        self.driver.find_element(By.XPATH, "//span[contains(.,'Geo Zones')]").click()

        # сформировать список стран
        count_row = len(self.driver.find_elements(By.XPATH, "//table[@class='dataTable']//tr[@class='row']"))
        list_zones = []
        for i in range(count_row):
            zone = self.driver.find_element(By.XPATH, f"//table[@class='dataTable']//tr[{i+2}]/td[3]/a").get_attribute(
                "textContent")
            list_zones.append(zone)
        # проверить сортировку стран
        assert list_zones == sorted(list_zones), "Список геозон на UI не отсортирован"


        for i in range(count_row):
            count_zone = self.driver.find_element(By.XPATH, f"//table[@class='dataTable']//tr[{i+2}]/td[4]").get_attribute(
                "textContent")
            # если найдены зоны
            if count_zone != '0':
                # перейти к списку зон
                self.driver.find_element(By.XPATH, f"//table[@class='dataTable']//tr[{i + 2}]/td[5]/a").click()

                # получить кол-во строк
                count_row = len(self.driver.find_elements(By.XPATH, "//table[@id='table-zones']//tr"))-2
                list_zones=[]
                for i in range(count_row):
                    # сформировать список зон
                    zone = self.driver.find_element(By.XPATH, f"//table[@id='table-zones']//tr[{i+2}]/td[3]//option[@selected='selected']").get_attribute("textContent")
                    list_zones.append(zone)
                assert list_zones == sorted(list_zones), "Список геозон на UI не отсортирован"
                self.driver.find_element(By.NAME, f"cancel").click()



    def login(self, email, password):
        self.driver.find_element(By.NAME, "email").send_keys(email)
        self.driver.find_element(By.NAME, "password").send_keys(password)
        self.driver.find_element(By.NAME, "login").click()

    def login_admin_panel(self, email, password):
        self.driver.find_element(By.NAME, "username").send_keys(email)
        self.driver.find_element(By.NAME, "password").send_keys(password)
        self.driver.find_element(By.NAME, "login").click()

    def logout(self):
        self.driver.find_element(By.XPATH, "//a[@href='http://localhost/litecart/public_html/en/logout']").click()


def clear(s):
    return re.sub("[() - : .]", "", s)
