# Generated by Selenium IDE
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import re


class Test:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def get_log(self):
        for l in self.driver.get_log("browser"):
            print(l)

    def find_and_fill_element(self, element_name, value):
        self.driver.find_element(By.NAME, element_name).clear()
        self.driver.find_element(By.NAME, element_name).send_keys(value)

    import re
    def test_error_in_browsers_log(self):
        self.driver.get("http://localhost/litecart/public_html/admin/")
        self.driver.implicitly_wait(60)
        self.find_and_fill_element(element_name="username", value="admin")
        self.find_and_fill_element(element_name="password", value="admin")
        self.driver.find_element(By.NAME, "login").click()
        print()

        self.driver.get("http://localhost/litecart/public_html/admin/?app=catalog&doc=catalog&category_id=1")

        all_items = self.driver.find_elements(By.XPATH, ".//*[@id='content']/form/table/tbody/tr/td[./img and ./a]/a")
        print(self.driver.log_types)

        for i in range(len(all_items)):
            all_items = self.driver.find_elements(By.XPATH, ".//*[@id='content']/form/table/tbody/tr/td[./img and ./a]/a")
            print(i)
            print(all_items[i].get_attribute('href'))

            all_items[i].click()

            for l in self.driver.get_log("browser"):
                print("Лог:", l)
            self.driver.find_element(By.NAME, "cancel").click()
